apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev
    build:
      local:
        push: true  # false는 로컬 테스트
      artifacts:
        - image: ${{ values.imageUrl }}/${{ values.repoName }}
          jib:
            args:
              - -DskipTests
            fromImage: openjdk:17-jdk-slim
